### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by 8hatch8** [8hatch8/protospace-37275#1]
# URL
https://protospace-37275.herokuapp.com

**Comment by snkw-works** [comment]
@8hatch8 さん、お待たせいたしました。ご提出ありがとうございます‼︎
正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）

**Comment by 8hatch8** [comment]
ありがとうございます！引き続きよろしくお願いします
